#!/usr/bin/env python3
"""
Build the warehouse fixture.

Deterministic on purpose. The seed is fixed, so the same file comes out every time and a test can
assert an exact number - which is the only way a fixture can prove an agent got the answer *right*
rather than merely got an answer. A fixture whose contents move can only ever check that a query ran.

It is also deliberately not clean. Every trap below is a way a plausible query returns a confident
wrong number, and the point of this agent is refusing exactly that:

  - cancelled orders, which are not revenue
  - refunds, which are partial and belong to an order in a different month than the refund
  - one order with no line items at all, so SUM over a join silently drops it
  - NULL country on two customers, so GROUP BY country loses rows a naive COUNT does not
  - a customer who signed up inside the window and never ordered
  - two orders one second either side of a month boundary, in UTC
  - a duplicated customer name that is two different people

The answers to the questions in README.md are computed at the bottom and printed, so the README and
the data cannot drift apart.
"""

import random
from datetime import datetime, timedelta

SEED = 20260824
random.seed(SEED)

START = datetime(2026, 2, 1)
DAYS = 180

COUNTRIES = ["IN", "US", "GB", "DE", "SG"]
PLANS = ["free", "starter", "growth", "scale"]
CHANNELS = ["web", "ios", "android", "partner"]

PRODUCTS = [
    ("SKU-CAM-01", "Doorbell camera", "hardware", 4200),
    ("SKU-CAM-02", "Indoor camera", "hardware", 2600),
    ("SKU-HUB-01", "Home hub", "hardware", 7400),
    ("SKU-SEN-01", "Door sensor", "hardware", 900),
    ("SKU-SEN-02", "Motion sensor", "hardware", 1100),
    ("SKU-SUB-01", "Monitoring, monthly", "subscription", 0),
    ("SKU-SUB-02", "Monitoring, annual", "subscription", 0),
    ("SKU-INS-01", "Professional install", "service", 3000),
]

PRICE = {
    "SKU-CAM-01": 9900, "SKU-CAM-02": 5900, "SKU-HUB-01": 14900, "SKU-SEN-01": 2400,
    "SKU-SEN-02": 2900, "SKU-SUB-01": 999, "SKU-SUB-02": 9900, "SKU-INS-01": 7500,
}

def iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")

def quote(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


customers, orders, items, refunds = [], [], [], []

for cid in range(1, 181):
    signed = START + timedelta(days=random.randint(0, DAYS - 1), hours=random.randint(0, 23))
    # Two customers with no country, so a GROUP BY country quietly loses them.
    country = None if cid in (37, 118) else random.choices(COUNTRIES, weights=[5, 4, 3, 2, 2])[0]
    name = f"Customer {cid:03d}"
    # The same name twice, two different people. Grouping by name merges them; grouping by id does not.
    if cid == 92:
        name = "Customer 041"
    customers.append((cid, name, country, iso(signed), random.choice(PLANS)))

oid = 1000
for cid, _name, _country, signed_iso, _plan in customers:
    signed = datetime.strptime(signed_iso, "%Y-%m-%dT%H:%M:%SZ")
    # A signup that never ordered: customer 77, inside the window, no orders at all.
    if cid == 77:
        continue
    for _ in range(random.randint(0, 12)):
        placed = signed + timedelta(days=random.randint(0, 150), hours=random.randint(0, 23))
        if placed > START + timedelta(days=DAYS):
            continue
        oid += 1
        status = random.choices(["paid", "paid", "paid", "paid", "cancelled"], k=1)[0]
        orders.append([oid, cid, iso(placed), status, random.choice(CHANNELS)])

        for sku, _n, _cat, _cost in random.sample(PRODUCTS, random.randint(1, 3)):
            items.append((oid, sku, random.randint(1, 3), PRICE[sku]))

# One order with no line items at all, so a SUM over the join drops it without saying so.
oid += 1
orders.append([oid, 12, iso(START + timedelta(days=90)), "paid", "web"])
EMPTY_ORDER = oid

# Two orders a second either side of a month boundary, in UTC.
for offset, label in ((-1, "just before"), (1, "just after")):
    oid += 1
    boundary = datetime(2026, 5, 1) + timedelta(seconds=offset)
    orders.append([oid, 5, iso(boundary), "paid", "web"])
    items.append((oid, "SKU-HUB-01", 1, PRICE["SKU-HUB-01"]))

# Refunds, partial, and dated after the order they belong to - sometimes in the next month.
paid = [o for o in orders if o[3] == "paid"]
for order in random.sample(paid, 46):
    placed = datetime.strptime(order[2], "%Y-%m-%dT%H:%M:%SZ")
    total = sum(q * p for (o, _s, q, p) in items if o == order[0])
    if total == 0:
        continue
    refunds.append((
        order[0],
        iso(placed + timedelta(days=random.randint(1, 40))),
        min(total, random.choice([total, total // 2, total // 4])),
        random.choice(["faulty", "changed mind", "late delivery", "duplicate order"]),
    ))

lines = [
    "-- Generated by generate.py. Do not edit by hand; edit the generator and re-run it.",
    "-- Deterministic: seed %d, so the same file comes out every time and a test can assert a number." % SEED,
    "",
    "PRAGMA foreign_keys = ON;",
    "",
    "DROP TABLE IF EXISTS refunds;",
    "DROP TABLE IF EXISTS order_items;",
    "DROP TABLE IF EXISTS orders;",
    "DROP TABLE IF EXISTS products;",
    "DROP TABLE IF EXISTS customers;",
    "",
    "CREATE TABLE customers (",
    "  id INTEGER PRIMARY KEY,",
    "  name TEXT NOT NULL,",
    "  country TEXT,            -- nullable on purpose: two rows have none",
    "  signed_up_at TEXT NOT NULL,",
    "  plan TEXT NOT NULL",
    ");",
    "",
    "CREATE TABLE products (",
    "  sku TEXT PRIMARY KEY,",
    "  name TEXT NOT NULL,",
    "  category TEXT NOT NULL,",
    "  unit_cost_cents INTEGER NOT NULL   -- zero for subscriptions, which have no unit cost",
    ");",
    "",
    "CREATE TABLE orders (",
    "  id INTEGER PRIMARY KEY,",
    "  customer_id INTEGER NOT NULL REFERENCES customers(id),",
    "  placed_at TEXT NOT NULL,",
    "  status TEXT NOT NULL,    -- 'paid' or 'cancelled'. Cancelled is not revenue.",
    "  channel TEXT NOT NULL",
    ");",
    "",
    "CREATE TABLE order_items (",
    "  order_id INTEGER NOT NULL REFERENCES orders(id),",
    "  sku TEXT NOT NULL REFERENCES products(sku),",
    "  quantity INTEGER NOT NULL,",
    "  unit_price_cents INTEGER NOT NULL",
    ");",
    "",
    "CREATE TABLE refunds (",
    "  order_id INTEGER NOT NULL REFERENCES orders(id),",
    "  refunded_at TEXT NOT NULL,   -- may fall in a later month than the order",
    "  amount_cents INTEGER NOT NULL,",
    "  reason TEXT NOT NULL",
    ");",
    "",
]

for sku, name, cat, cost in PRODUCTS:
    lines.append(f"INSERT INTO products VALUES ({quote(sku)}, {quote(name)}, {quote(cat)}, {cost});")
lines.append("")

for cid, name, country, signed, plan in customers:
    lines.append(
        f"INSERT INTO customers VALUES ({cid}, {quote(name)}, {quote(country)}, {quote(signed)}, {quote(plan)});"
    )
lines.append("")

for oid_, cid, placed, status, channel in orders:
    lines.append(
        f"INSERT INTO orders VALUES ({oid_}, {cid}, {quote(placed)}, {quote(status)}, {quote(channel)});"
    )
lines.append("")

for order_id, sku, qty, price in items:
    lines.append(f"INSERT INTO order_items VALUES ({order_id}, {quote(sku)}, {qty}, {price});")
lines.append("")

for order_id, at, amount, reason in refunds:
    lines.append(f"INSERT INTO refunds VALUES ({order_id}, {quote(at)}, {amount}, {quote(reason)});")
lines.append("")

with open("seed.sql", "w") as handle:
    handle.write("\n".join(lines))

# The known-correct answers, so the README and the data cannot drift apart.
paid_ids = {o[0] for o in orders if o[3] == "paid"}
gross = sum(q * p for (o, _s, q, p) in items if o in paid_ids)
refunded = sum(a for (o, _t, a, _r) in refunds if o in paid_ids)

print(f"customers      {len(customers)}")
print(f"orders         {len(orders)}  ({len(paid_ids)} paid, {len(orders) - len(paid_ids)} cancelled)")
print(f"order_items    {len(items)}")
print(f"refunds        {len(refunds)}")
print(f"gross_paid_cents    {gross}")
print(f"refunded_cents      {refunded}")
print(f"net_revenue_cents   {gross - refunded}")
print(f"order with no items {EMPTY_ORDER}")
